name: aucorsa
description: "Simple yet beautiful, public transport app for Cordoba, Spain."
publish_to: 'none'
version: 1.4.0+11

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  compassx: ^1.0.1
  dio: ^5.7.0
  duration: ^4.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^6.0.0
  flutter_inappwebview: ^6.2.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_location_marker: ^10.1.0
  flutter_map_math: ^0.2.1
  geolocator: ^14.0.1
  go_router: ^17.0.0
  go_transitions: ^0.8.3
  google_fonts: ^6.2.1
  html: ^0.15.5
  hydrated_bloc: ^10.0.0
  in_app_review: ^2.0.10
  intl: ^0.20.2
  latlong2: ^0.9.1
  lucky_navigation_bar: ^1.0.0
  material_symbols_icons: ^4.2873.0
  nfc_manager: ^4.0.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  vector_map_tiles: 9.0.0-beta.8
  vector_tile_renderer: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  image_path: assets/icons/icon_app.png

  ios: true
  remove_alpha_ios: true
  image_path_ios_dark_transparent: assets/icons/icon_app_foreground.png
  image_path_ios_tinted_grayscale: assets/icons/icon_app_grayscale.png
  background_color_ios: "#FFFFFF"

  android: true
  adaptive_icon_foreground: assets/icons/icon_app_foreground.png
  adaptive_icon_monochrome: "assets/icons/icon_app_grayscale.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  image: assets/icons/icon_app_foreground.png
  color: "#F8FBF2"
  color_dark: "#11140F"

  android_12:
    color: "#F8FBF2"
    color_dark: "#11140F"
    icon_background_color: "#F8FBF2"
    icon_background_color_dark: "#11140F"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/vector-map-tiles/
    - assets/vector-map-styles/
    - .env
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
